### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by emilmork** [mikaelbr/SocialFeed.js#5]
I tend to get a random TypeError. Happens now and then.

Uncaught TypeError: undefined is not a function - line 630 in socialfeed.js.

Found this on your personal page as well - line 102 in controller.js

![skjermbilde 2014-05-13 kl 20 44 25](https://cloud.githubusercontent.com/assets/1029158/2963801/5a5925b4-dadf-11e3-866f-fdf0bf12c29b.png)

**Comment by mikaelbr** [comment]
I couldn't replicate it, but it seems to be a problem when a module couldn't load (be it AJAX fault or something), and the collection would be undefined or not a collection. I've added a null-check for this. The new version is `v0.4.1`. Please let me know if the problem persists (and re-open this issue).
